name: mi_proyecto_dart # Nombre de tu proyecto
description: Una descripción de tu proyecto.
version: 1.0.0
# homepage: https://www.ejemplo.com

environment:
  sdk: ">=3.0.0 <4.0.0" # Versión mínima y máxima del SDK de Dart que tu proyecto soporta

dependencies:
  io: ^1.0.5
  http: ^0.13.5
  # Agrega tus dependencias aquí, por ejemplo:
  # vector_math: ^2.1.3
  # http: ^1.0.0

dev_dependencies:
  # Dependencias para el desarrollo, por ejemplo:
  # test: ^1.24.0